export const FIND_LOCATIONS_REQUEST = 'locations/FIND_LOCATIONS_REQUEST';
export const FIND_LOCATIONS_SUCCESS = 'locations/FIND_LOCATIONS_SUCCESS';
export const FIND_LOCATIONS_FAILURE = 'locations/FIND_LOCATIONS_FAILURE';